name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: 18256485741 # 这个是阿里云登录账号
        password: Fzz160903 # 这个是acr访问凭证中设置的固定密码
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/mysql@sha256:81e9d95d528511718b81cb9c548e1b922976bf359ed1083782bdbbbccf9ad85d docker://registry.cn-hangzhou.aliyuncs.com/dbfu/mysql:latest
         skopeo copy docker://docker.io/node:16.16.0 docker://registry.cn-hangzhou.aliyuncs.com/dbfu/node:16.16.0
         skopeo --override-arch arm64 copy docker://docker.io/bitnami/minio:latest docker://registry.cn-hangzhou.aliyuncs.com/dbfu/minio-arm64:latest
         skopeo --override-arch arm64 copy docker://docker.io/timotto/rpi-minio:latest docker://registry.cn-hangzhou.aliyuncs.com/dbfu/rpi-minio:latest
         skopeo copy docker://docker.io/portainer/portainer-ce:linux-arm64-2.20.3 docker://registry.cn-hangzhou.aliyuncs.com/dbfu/portainer-ce:linux-arm64-2.20.3
         skopeo copy docker://docker.io/minio/minio:RELEASE.2020-11-25T22-36-25Z-arm64 docker://registry.cn-hangzhou.aliyuncs.com/dbfu/minio-new-arm:latest
         skopeo copy docker://docker.io/jeessy/ddns-go@sha256:e3b561d43da7b85b0af916c5f2b3dff7bd9bdf3cffa42ba0b21bcfc1e52566b7 docker://registry.cn-hangzhou.aliyuncs.com/dbfu/ddns-go-arm:latest
         

      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称 

