name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.ALIYUN_REGISTRY_USER }}"
        password: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" 
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/nginxproxy/nginx-proxy:latest docker://registry.cn-hangzhou.aliyuncs.com/dbfu/nginx-proxy:latest
         skopeo copy docker://docker.io/nginxproxy/acme-companion:latest docker://registry.cn-hangzhou.aliyuncs.com/dbfu/acme-companion:latest
         skopeo copy docker://docker.io/redis:latest docker://registry.cn-hangzhou.aliyuncs.com/dbfu/redis:latest
         skopeo copy docker://docker.io/mysql:latest docker://registry.cn-hangzhou.aliyuncs.com/dbfu/mysql:latest
         skopeo copy docker://docker.io/minio/minio:latest docker://registry.cn-hangzhou.aliyuncs.com/dbfu/minio:latest
         
         


